### ISSUE TITLE
The input smiles is long and the model cannot load out the dialog box that the user asks

### ISSUE THREAD

**Issue by hzau96yhz** [UCSD-AI4H/drugchat#15]
Hello, I would like to ask a question. During training, I set max_epoch to 1 in the drugchat_stage2_finetune.yaml configuration file. After that, I ran the demo app, but for the smiles string input, there was a phenomenon that the app didn't seem to load the user when the smiles was long. When smiles is short, the program can load the user inquiry dialog box faster. The two smiles strings `COc1ccc2c(c1)c(CN1CCN(C)CC1)cn2S(=O)(=O)c1ccccc1Br` and `CC` are entered, and the results are shown in the figure, respectively.
1)input smiles: `COc1ccc2c(c1)c(CN1CCN(C)CC1)cn2S(=O)(=O)c1ccccc1Br`
![QQ图片20230924185159](https://github.com/UCSD-AI4H/drugchat/assets/53745234/80b5c002-3278-4ac1-b7d7-88e50daeabee)
2)input smiles: `CC`
![QQ图片20230924191132](https://github.com/UCSD-AI4H/drugchat/assets/53745234/1db73464-d78f-422f-a3fb-3731844775e8)
Is the reason for the inadequate training of the projection layer？Or because of insufficient GPU memory？（I used 48G）

**Comment by youweiliang** [comment]
This is quite strange. It shouldn't be the case because we tested longer smiles and it still worked. It is probably not because of inadequate training or insufficient memory, because your screenshot showed the smiles was not converted to graph correctly. Could you put several prints between the lines in https://github.com/UCSD-AI4H/drugchat/blob/ad336e7922c304639fd1e61a0f3688723c0dfdea/dataset/smiles2graph_demo.py#L92-L110 to pinpoint the issue.

**Comment by hzau96yhz** [comment]
Hi！Thank you for your reply! I tried again a few days ago and the problem was solved. I didn't change any of the code, and I suspect there might be some issue with the network or the gradio library. Thanks again!
